# Settings
title: HgO.Log
description: 
crawlertitle: "HgO.Log"
url: "http://hgo-git.github.io"
baseurl: ""

github_username: HgO-git

# Post file nameing
permalink: :categories/:year/:month/:day/:hour/:minute/:title

# Theme
sass:
  sass_dir: _sass
  style: compressed
