# Settings
title: HgO.Log
description: 
crawlertitle: "HgO.Log"
url: "http://hgo-git.github.io"
baseurl: ""
language: 'kr-ko'
timezone: Asia/Seoul
paginate: 4

github_username: HgO-git

# Post file nameing
permalink: :categories/:year/:month/:day/:hour/:minute/:title

# Theme
sass:
  sass_dir: _sass
  style: compressed

markdown : kramdown
highlighter : rouge
kramdown :
  input : GFM 
  syntax_highlighter: rouge
  syntax_highlighter_opts : 
    default_lang : c 
    css_class : 'syntax'
    span:
      line_numbers: false
    block:
      line_numbers: false
      # start_line: 0